### ISSUE TITLE
review: quick glance

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/Splitter#1]
##### Potential Improvs

- [x] would it make sense to make [splitTransfer](https://github.com/gitcoinco/Splitter/blob/master/contracts/Splitter.sol#L8) an `external` function as opposed to a `public` ? I read that it takes less gas and we know this function is not going to be used internally 
- [ ] should we add `modifier` / `assert` ensuring we invoke the `ERC20.transferFrom` if `valueFirst` & `valueSecond` are not `0` ?
- [ ] should we emit an `event` after each successfull transaction is done. I know it would be taken care in the `ERC20` contract but still? 
- [ ] should we come up with better variable names `toFirst`  & `valueFirst` ?  

##### Not needed at this point but just popped into my head

would it make sense to iterate on this to make it reusable for bounties  
- supporting ETH tokens
- mix and match of diff ERC20 / ETH tokens.
- allowing more than two splits ( for advanced payout ). Maybe keep an upper limit of 5?

cc @owocki / @danlipert

**Comment by owocki** [comment]
looks liek splitTransfer() requires someone to have previously `approve()`ed a transfer on the token contract address. is that right?

should we wrap `ERC20(tokenAddress).transferFrom()` in a require()?

should we check the bbalance before we invoke transfer?

**Comment by danlipert** [comment]
@thelostone-mc I changed the function from `public` to `external` - nice suggestion! Regarding the assert ensuring that the values aren't zero I suppose we could do that, but it would be extra gas for each call, and the underlying ERC20 contracts should ensure its a positive value. Events also increase gas, but we can add one if we have a good reason to. Regarding the variable names, let me know what you think would be a better naming convention.

@owocki This will require someone to `approve()` first, unfortunately. I don't think theres any other way we can do it, as theres no `payable` type of interface for ERC20 where we could trigger a function call when someone transfers an ERC20 token to this contract. Regarding checking the balance and adding a `require`, happy to add those if you think its neccessary, but I think its a bit redundant as the ERC20 contract will have a `require` or SafeMath `sub()` call protecting the balance ledger.

**Comment by owocki** [comment]
> but I think its a bit redundant as the ERC20 contract will have a require or SafeMath sub() call protecting the balance ledger.

Ahh !  I ran into this when I built the first version of bounties (before standard bounties).  not *all* ERC20 implementations follow the spec to a t do a require and use safemath :)

> I don't think theres any other way we can do it

Theres no way to do the `approve()` inline right?

I guess the only other way would be to pay the splitter contract the tokens, then allow each of the recipients to debit the splitter contract?  Your way is certainly simpler.

**Comment by danlipert** [comment]
@owocki Unfortunately we can't do the `approve()` inline since it typically uses `msg.sender` to determine who is `approve()`-ing the token spend, and in this case that would be the contract that called it. Also that is horrifying that not all ERC20 tokens check to make sure you don't get a negative balance :O I'll add that check to our contract here

**Comment by owocki** [comment]
> Unfortunately we can't do the approve() inline since it typically uses msg.sender to determine who is approve()-ing the token spend, and in this case that would be the contract that called it.

IIRC there is a way to call a sub contract, but with the parent contracts scope.  i forget the name of the function, but i recall that John Mardlin from Consensys Dilligence had told me about it.

**Comment by thelostone-mc** [comment]
Closing this out as we've got the base setup done which seems to be
